# This is a basic workflow to help you get started with Actions

name: test-docker

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Thomas
      - name: date
        run: date
      - name: secret
        shell: bash
        env:
          MYSECRET: ${{ secrets.MYSECRET }}        
        run: python3 -c "import os;print(os.environ['MYSECRET'])" # GitHub replaces all secrets in the output with ***, really everything
      - name: do a code check
        run: true # replace true <-> false

# https://github.com/wshihadeh/docker-deployment-action
# https://github.com/wshihadeh/docker-deployment-action/blob/master/docker-entrypoint.sh
# ssh_public_key -> ssh-keyscan -p 3000 <host>
# ssh_private_key -> see how to generate via https://github.com/wshihadeh/docker-deployment-action e.g.
# ssh-keygen -p -m PEM -f ~/.ssh/id_rsa
# ssh-keygen -t rsa -b 4096 -m pem
# do not use anypassword

      - name: Start Deployment
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: ${{ secrets.DOCKER_HOST }}
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }} # seems be ok if just a single space/empty?
          remote_docker_port: ${{ secrets.DOCKER_PORT }}
          stack_file_name: docker-compose.yml
#          copy_stack_file: true
#          pull_images_first: true
          args: up
       
#      - name: Start Deployment
#        uses: TapTap21/docker-remote-deployment-action@v1.0
#        with:
#          remote_docker_host: ${{ secrets.DOCKER_HOST }}
#          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
#          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
#          ssh_port: 3000
#          args: up
